# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a267148be961cb4801e19692adc98e50f541f4808aa3923c61cff125c7caab6ceee9b8a0141fdc97ca9da482da1f5ac97d3a480e58cbc5a3961120a1fb344c9

test:
  secret_key_base: b19c10ff45f3424481c107203185a5ba7bc206b4675a29c33adabc0403e47254a7ed779c613f5204182bac3b8ae123d64b8c694a9fee974edc7f99a19b7c0176

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
